#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x939E6BE1E29FC3CC (grothoff@gnunet.org)
#
Name     : libmicrohttpd
Version  : 0.9.54
Release  : 13
URL      : http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.54.tar.gz
Source0  : http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.54.tar.gz
Source99 : http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.54.tar.gz.sig
Summary  : A library for creating an embedded HTTP server
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmicrohttpd-lib
Requires: libmicrohttpd-doc
BuildRequires : curl-dev
BuildRequires : gnutls-dev
BuildRequires : libgcrypt-dev
BuildRequires : texinfo

%description
About
=====
GNU libmicrohttpd is a GNU package offering a C library that provides
a compact API and implementation of an HTTP 1.1 web server (HTTP 1.0
is also supported).  GNU libmicrohttpd only implements the HTTP 1.1
protocol.  The main application must still provide the application
logic to generate the content.

%package dev
Summary: dev components for the libmicrohttpd package.
Group: Development
Requires: libmicrohttpd-lib
Provides: libmicrohttpd-devel

%description dev
dev components for the libmicrohttpd package.


%package doc
Summary: doc components for the libmicrohttpd package.
Group: Documentation

%description doc
doc components for the libmicrohttpd package.


%package lib
Summary: lib components for the libmicrohttpd package.
Group: Libraries

%description lib
lib components for the libmicrohttpd package.


%prep
%setup -q -n libmicrohttpd-0.9.54

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494268384
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1494268384
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libmicrohttpd.so
/usr/lib64/pkgconfig/libmicrohttpd.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmicrohttpd.so.12
/usr/lib64/libmicrohttpd.so.12.42.0
